openapi: 3.0.0
info:
  title: Tenant API
  version: v2
paths:
  /books:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    post:
      description: Create book
      operationId: postBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: schemas/book.json
        required: true
      responses:
        "204":
          description: Book created
        "400":
          $ref: "#/components/responses/trait_400"
        "413":
          $ref: "#/components/responses/trait_413"
        "500":
          $ref: "#/components/responses/trait_500"
    get:
      description: Get books
      operationId: getBooks
      parameters:
      - in: query
        name: query
        required: false
        description: CQL
        schema:
          type: string
      responses:
        "200":
          description: Books returned
          content:
            application/json:
              schema:
                $ref: schemas/books.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /books/{id}:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: book identifier
        schema:
          type: string
          format: uuid
    get:
      operationId: getBook
      description: Get book
      responses:
        "200":
          description: Books returned
          content:
            application/json:
              schema:
                $ref: schemas/book.json
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

components:
  responses:
    trait_400:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid JSON in request
        application/json:
          schema:
            type: object
            example: {"error":"Invalid JSON in request"}
    trait_404:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Not found
    trait_413:
      description: Payload Too Large
      content:
        text/plain:
          schema:
            type: string
            example: Payload Too Large
    trait_500:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error, contact administrator

